### ISSUE TITLE
Local Server Install Problem

### ISSUE THREAD

**Issue by DesistDaydream** [WH-2099/dst-server#3]
run cmd:

```bash
docker run --name dst -d --restart unless-stopped --network host \
  -v /opt/dst-server/MyDediServer:/cluster \
  -v /opt/dst-server/install:/install \
  --env HTTP_PROXY="http://100.64.0.3:7890 \
  --env HTTPS_PROXY="http://100.64.0.3:7890 \ 
  wh2099/dst-server:latest
```

/entrypoint.sh: line 56: cd: /install/bin64: No such file or directory

If I manually create the bin64 directory, There will be other dir that cannot be detected, e.g. dontstarve_dedicated_server_nullrenderer_x64, etc.

**Comment by WH-2099** [comment]
It seems that this is caused by the built-in mirror script failing to successfully install the game server itself.
Please post the logs in the container, you can view them with this command:

```bash
docker logs dst
```

By the way, I noticed that you have set up environment variable proxies, unfortunately :rofl:, since `steamcmd` doesn't support proxy settings via environment variables, this doesn't actually have an effect.

**Comment by DesistDaydream** [comment]
If the proxy does not work, does that mean that the STEAMCMD execution actually failed?

The following is the docker log:

```text
~]# docker run --name dst --restart unless-stopped --network host -v /opt/dst-server/MyDediServer:/cluster -v /opt/dst-server/install:/install --env HTTP_PROXY="http://100.64.0.3:7890 --env HTTPS_PROXY="http://100.64.0.3:7890  wh2099/dst-server:latest
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Logging directory: '/root/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
UpdateUI: skip show logosteamcmd.sh[8]: Restarting steamcmd by request...
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Logging directory: '/root/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1728594755
-- type 'quit' to exit --
Loading Steam API...OK
"@ShutdownOnFailedCommand" = "1"
"@NoPromptForPassword" = "1"

Connecting anonymously to Steam Public...
Retrying. . . 
Retrying. . . 
Retrying. . . 
OK
Waiting for client config...OK
Waiting for user info...OK
/entrypoint.sh: line 56: cd: /install/bin64: No such file or directory
Error: can't cd to /install/bin64
```

**Comment by WH-2099** [comment]
This looks like it's caused by the server failing to install automatically, and I'm not quite sure what the exact problem is here (but I'm guessing it's more or less network related).

#### Server Install

I wrote a command for you (assuming you want to install the game server files in the `/opt/dst-server/install` directory): 

```bash
docker run --rm -v /opt/dst-server/install:/install -w /steamcmd --network hostdocker.io/wh2099/dst-server /steamcmd/steamcmd.sh +force_install_dir /install +login anonymous +app_update 343050 validate +quit
```

The above command creates a temporary container to install the game server and forces the validation of the local files by adding the `validate` parameter to steamcmd. If the installation reports an error, you can try running it a few more times (it's idempotent) for the reasons I've added below.

#### About Network

Actually your first implicit concern is in the right direction, steam's connection to its authentication servers is not stable in your network environment (it was for me too, it's a thing gamers are used to in China), the solution is simple, you can always connect after 3-5 retries.

Currently the script in the image tries to update the server automatically every time it starts, but this is not necessary, if you can be sure that the current game server does not need to be updated (compare `install/version.txt` with [DST GAME UPDATE](https://forums.kleientertainment.com/game-updates/dst/)), you can skip the automatic update at each startup by creating a file called `noupdate` in the directory corresponding to `install/`.

**Comment by DesistDaydream** [comment]
I'm going to try the method you provided now.


I tried the following method a while ago

```bash
docker run -it --name=test-steamcmd --network=host cm2network/steamcmd bash
```
create [run_dedicated_servers.sh](https://accounts.klei.com/assets/gamesetup/linux/run_dedicated_servers.sh)

add config files

![image](https://github.com/user-attachments/assets/da749b98-0c3b-429b-9f49-613a63033240)

After resolving some errors, such as installing libcurl-gnutls.so.4, results are as following:

```bash
~$ ./run_dedicated_servers.sh 
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1728594755
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...Retrying. . . 
Retrying. . . 
Retrying. . . 
Retrying. . . 
OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) verifying install, progress: 8.12 (313243169 / 3857476730)
 Update state (0x5) verifying install, progress: 17.49 (674540595 / 3857476730)
...... too many logs
Master: [00:00:07]: Check for write access: FALSE
Master: [00:00:07]: Reset() returning
Master: [00:00:07]: THREAD - started 'WorldSim' (140186423867072)
Master: [00:00:07]: WorldSim::SimThread::Main()
Master: [00:00:07]: DoLuaFile scripts/worldgen_main.lua
Master: [00:00:07]: DoLuaFile loading buffer scripts/worldgen_main.lua
Master: [00:00:07]: DLC enabled :       false
src/tier1/fileio.cpp (5086) : m_vecRegisteredWriters.Count() == 0
Caves:  src/tier1/fileio.cpp (5086) : m_vecRegisteredWriters.Count() == 0
src/tier1/fileio.cpp (5086) : m_vecRegisteredWriters.Count() == 0
Master: src/tier1/fileio.cpp (5086) : m_vecRegisteredWriters.Count() == 0
```

I may also need to solve the running dependency problem of DST itself

**Comment by WH-2099** [comment]
Sorry for taking more time to write a reply, you can try the way I mentioned above, after installing the game server file, the image should work fine, and there's no need to solve the dependency environment problem locally.

**Comment by DesistDaydream** [comment]
用英文是不是给你造成困扰了。。实在抱歉~

上面提到的方法可以正常安装游戏

```bash
]# docker run --rm -v /opt/dst-server/install:/install -w /steamcmd --network host docker.io/wh2099/dst-server /steamcmd/steamcmd.sh +force_install_dir /install +login anonymous +app_update 343050 validate +quit
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Logging directory: '/root/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
......略
 Update state (0x5) verifying install, progress: 89.46 (3450751126 / 3857476730)
 Update state (0x5) verifying install, progress: 99.34 (3831903522 / 3857476730)
IPC function call IClientAppManager::GetUpdateInfo took too long: 58 msec
Success! App '343050' fully installed.
```

**Comment by WH-2099** [comment]
没关系，语言都很好翻译互转。😸

事实上这个项目攒了一些本地改动没有提交，所以当前的版本确实还有待完善，后续会逐步补充上来。 

---

It's okay, the languages are all pretty well translated and interchanged.😸

The fact that this project saved up some local changes and didn't submit them, so the current version does still need to be improved, will gradually add up later.

**Comment by DesistDaydream** [comment]
确实还是网络问题，我只是现在重新运行了一下

```bash
docker run --name dst -d --restart unless-stopped --network host \
-v /opt/dst-server/MyDediServer:/cluster \
-v /opt/dst-server/install:/install \
wh2099/dst-server:latest
```

已经正常了

![image](https://github.com/user-attachments/assets/7d61ecef-455d-4807-9729-838ce423cad4)
